#!/usr/bin/env python

from image_fft import cli_main

if __name__ == '__main__':
    cli_main()
else:
    import sys
    print('This module is an entry point and should not be imported!', file=sys.stderr)
    sys.exit(1)
